project:
  type: website

website:
  title: "Single cell Single molecule - scRNA analysis"
  navbar:
    logo: /img/logo.png
    left:
      - href: index.qmd
        text: Introduction
      - href: tutorial.qmd
        text: Tutorial
      - href: filtering.qmd
        text: Filtering
      - href: integration.qmd
        text: Integration
      - href: nb/tutorial-2024.ipynb
        text: Tutorial Code
    right: 
      - icon: github
        href: https://github.com/SamueleSoraggi/scsm
        aria-label: GitHub

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
#    include-in-header:
#      - file: "resources/bioschema.html"
