project:
  type: website

website:
  title: "Single cell Single molecule course"
  description: "Single Cell Transcriptomics analysis for the Single-cell and -molecule course"
  navbar:
    logo: /img/logo.png
    left:
      - href: index.qmd
        text: Introduction
      - href: alignandclean.qmd
        text: Alignment
      - href: tutorial.qmd
        text: Analysis
      - href: filtering.qmd
        text: Filtering
      - href: integration.qmd
        text: Integration
      - sidebar:code
      #- href: nb/Cleaningthedata.source.ipynb
      #  text: Alignment Code
      #- href: nb/tutorial-2024.ipynb
      #  text: Analysis Code
    right: 
      - icon: github
        href: https://github.com/SamueleSoraggi/scsm
        aria-label: GitHub
  sidebar:
    - id: code
      title: "Code"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - nb/Cleaningthedata.source.ipynb
        - nb/tutorial-2024.ipynb
format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
#    include-in-header:
#      - file: "resources/bioschema.html"
